//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayTinhDaiPhat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonXuat
    {
        public int MaCTHDX { get; set; }
        public Nullable<int> MaHDX { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public Nullable<int> MaHTTT { get; set; }
        public Nullable<int> MaTTDH { get; set; }
    
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual HoaDonXuat HoaDonXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
    }
}
