//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayTinhDaiPhat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDonNhap = new HashSet<ChiTietHoaDonNhap>();
            this.ChiTietHoaDonXuat = new HashSet<ChiTietHoaDonXuat>();
            this.HinhAnh = new HashSet<HinhAnh>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaTH { get; set; }
        public Nullable<int> MaDM { get; set; }
        public string TenSP { get; set; }
        public string AnhSP { get; set; }
        public string MoTa { get; set; }
        public string KhuyenMai { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaCu { get; set; }
        public Nullable<int> BaoHanh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonNhap> ChiTietHoaDonNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonXuat> ChiTietHoaDonXuat { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnh { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
