//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayTinhDaiPhat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int MaSlide { get; set; }
        public string TenSlide { get; set; }
        public string AnhSlide { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
